CREATE TABLE bookmarks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title text NOT NULL,
    url text NOT NULL,
    description text,
    rating decimal(1, 0) CHECK (rating <= 5 AND rating >= 0) NOT NULL
);